INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (48460, NULL, 'Life', 'life', 'stateofmatter');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1, 48460, 'Animalia', 'Animals', 'kingdom');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (2, 1, 'Chordata', 'Chordates', 'phylum');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (355675, 2, 'Vertebrata', 'Vertebrates', 'subphylum');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (40151, 355675, 'Mammalia', 'Mammals', 'class');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41573, 848324, 'Carnivora', 'Carnivorans', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41770, 41573, 'Mustelidae', 'Mustelids', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41775, 526556, 'Lontra', 'New World River Otters', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41777, 41775, 'Lontra canadensis', 'North American River Otter', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (848317, 40151, 'Theria', 'Therians', 'subclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (848320, 848317, 'Placentalia', 'Placental Mammals', 'infraclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (848324, 848320, 'Laurasiatheria', 'Ungulates, Carnivorans, and Allies', 'superorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (526556, 41770, 'Lutrinae', 'Otters', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (236798, 41777, 'Lontra canadensis pacifica', 'Western River Otter', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (201557, 41777, 'Lontra canadensis lataxina', 'Southeastern River Otter', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (939769, 41777, 'Lontra canadensis periclyzomae', 'Haida Gwaii River Otter', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1248936, 41777, 'Lontra canadensis canadensis', 'Northeastern River Otter', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (236795, 41777, 'Lontra canadensis kodiacensis', 'Kodiak Island River Otter', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (236797, 41777, 'Lontra canadensis mira', 'Prince of Wales River Otter', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (211197, 41777, 'Lontra canadensis sonora', 'Southwestern River Otter', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41859, 526556, 'Enhydra', 'sea otters', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41860, 41859, 'Enhydra lutris', 'Sea Otter', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (133061, 41860, 'Enhydra lutris kenyoni', 'Northern Sea Otter', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (3, 355675, 'Aves', 'Birds', 'class');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (2114, 3, 'Coraciiformes', 'Kingfishers, Bee-eaters, Rollers And Allies', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (2314, 2114, 'Alcedinidae', 'Kingfishers', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1623, 3, 'Cuculiformes', 'Cuckoos', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1627, 1623, 'Cuculidae', 'Cuckoos', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1628, 1541352, 'Centropus', 'Coucals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (2422, 1542375, 'Actenoides', 'Wood Kingfishers', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (2427, 2422, 'Actenoides monachus', 'Green-backed Kingfisher', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1653, 1628, 'Centropus monachus', 'Blue-headed Coucal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (5067, 71261, 'Accipitridae', 'Hawks, Eagles, and Kites', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (4262, 71268, 'Phalacrocoracidae', 'Cormorants and Shags', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (3806, 67564, 'Spheniscidae', 'Penguins', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (5380, 1541533, 'Aegypius', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (3807, 3806, 'Pygoscelis', 'Brush-tailed Penguins', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (3808, 3807, 'Pygoscelis papua', 'Gentoo Penguin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (3819, 3806, 'Aptenodytes', 'Great Penguins', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (3821, 3819, 'Aptenodytes patagonicus', 'King Penguin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (3810, 3807, 'Pygoscelis adeliae', 'Adelie Penguin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (3820, 3819, 'Aptenodytes forsteri', 'Emperor Penguin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (7251, 3, 'Passeriformes', 'Perching Birds', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (16768, 980017, 'Tyrannus', 'Kingbirds', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (12160, 7251, 'Meliphagidae', 'Honeyeaters', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (8073, 71296, 'Artamus', 'Woodswallows', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (12319, 12160, 'Philemon', 'Typical Friarbirds', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (5382, 5380, 'Aegypius monachus', 'Cinereous Vulture', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (12329, 12319, 'Philemon corniculatus', 'Noisy Friarbird', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (5425, 1541533, 'Necrosyrtes', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (5426, 5425, 'Necrosyrtes monachus', 'Hooded Vulture', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (8074, 8073, 'Artamus monachus', 'Ivory-backed Woodswallow', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (26036, 355675, 'Reptilia', 'Reptiles', 'class');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (26172, 26036, 'Squamata', 'Snakes and Lizards', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (18874, 3, 'Psittaciformes', 'Parrots', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (18875, 18874, 'Psittacidae', 'New World and African Parrots', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (30403, 85553, 'Elapidae', 'Elapid Snakes', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (19348, 18875, 'Myiopsitta', 'Monk Parakeets', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (19349, 19348, 'Myiopsitta monachus', 'Monk Parakeet', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (32805, 1567778, 'Chamaeleonidae', 'Chameleons', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (32806, 32805, 'Chamaeleo', 'Typical Chameleons', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (16793, 16768, 'Tyrannus savana', 'Fork-tailed Flycatcher', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39532, 26036, 'Testudines', 'Turtles and Tortoises', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (33177, 371057, 'Gekkonidae', 'Typical Geckos', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39657, 372234, 'Cheloniidae', 'Typical Sea Turtles', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39658, 1366913, 'Chelonia', 'Green Sea Turtles', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39659, 39658, 'Chelonia mydas', 'Green Sea Turtle', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (34591, 33177, 'Gekko', 'Calling Geckos', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39664, 797541, 'Caretta', 'Loggerhead sea turtles', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (34610, 34591, 'Gekko monarchus', 'Double-spotted Gecko', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (35099, 492346, 'Suta', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (32832, 32806, 'Chamaeleo monachus', 'Socotran Chameleon', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39665, 39664, 'Caretta caretta', 'Loggerhead Sea Turtle', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39671, 797541, 'Eretmochelys', 'Hawksbill Sea Turtles', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39672, 39671, 'Eretmochelys imbricata', 'Hawksbill Sea Turtle', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39669, 797541, 'Lepidochelys', 'Ridley Sea Turtles', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39670, 39669, 'Lepidochelys olivacea', 'Olive Ridley Sea Turtle', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39675, 372234, 'Dermochelyidae', 'Leatherback Sea Turtles', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39676, 39675, 'Dermochelys', 'Leatherback Sea Turtles', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (39677, 39676, 'Dermochelys coriacea', 'Leatherback Sea Turtle', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41401, 1317256, 'Ziphiidae', 'Beaked Whales', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41402, 41401, 'Mesoplodon', 'Mesoplodont Beaked Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41419, 41401, 'Hyperoodon', 'Bottlenose Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41421, 41419, 'Hyperoodon ampullatus', 'North Atlantic Bottlenose Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41413, 41402, 'Mesoplodon bidens', 'North Atlantic Beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41407, 41402, 'Mesoplodon europaeus', 'Gulf Stream Beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41408, 41402, 'Mesoplodon densirostris', 'Dense-beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41420, 41419, 'Hyperoodon planifrons', 'Southern Bottlenose Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41409, 41402, 'Mesoplodon layardii', 'Strap-toothed Beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41405, 41402, 'Mesoplodon grayi', 'Gray''s Beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41417, 41401, 'Indopacetus', 'Indo-Pacific Beaked Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41418, 41417, 'Indopacetus pacificus', 'Indo-Pacific Beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41437, 1317261, 'Phocoenidae', 'Porpoises', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41438, 41437, 'Phocoena', 'Typical Porpoises', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41434, 1317258, 'Physeteridae', 'True Sperm Whales', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41435, 41434, 'Physeter', 'True Sperm Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41427, 41401, 'Ziphius', 'Goose-beaked Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41428, 41427, 'Ziphius cavirostris', 'Cuvier''s Beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41424, 41401, 'Berardius', 'Giant Beaked Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41439, 41438, 'Phocoena spinipinnis', 'Burmeister''s Porpoise', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41426, 41424, 'Berardius bairdii', 'Baird''s Beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41425, 41424, 'Berardius arnuxii', 'Arnoux''s Beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41440, 41438, 'Phocoena phocoena', 'Harbor Porpoise', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41457, 1317261, 'Monodontidae', 'Narwhals and Belugas', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41460, 41457, 'Delphinapterus', 'Belugas', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41461, 41460, 'Delphinapterus leucas', 'Beluga', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41445, 41437, 'Phocoenoides', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41446, 41445, 'Phocoenoides dalli', 'Dall''s Porpoise', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41458, 41457, 'Monodon', 'Narwhals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41459, 41458, 'Monodon monoceros', 'Narwhal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41443, 41438, 'Phocoena sinus', 'Vaquita', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41444, 41438, 'Phocoena dioptrica', 'Spectacled Porpoise', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41476, 424321, 'Eschrichtiidae', 'Grey Whales', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41477, 41476, 'Eschrichtius', 'Grey whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41466, 1317260, 'Iniidae', 'South American River Dolphins', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41471, 41466, 'Inia', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41472, 41471, 'Inia geoffrensis', 'Boto', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41469, 846059, 'Pontoporia', 'Franciscanas', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41470, 41469, 'Pontoporia blainvillei', 'Franciscana', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41463, 846055, 'Kogia', 'Dwarf and Pygmy Sperm Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41464, 41463, 'Kogia breviceps', 'Pygmy Sperm Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41465, 41463, 'Kogia sima', 'Dwarf Sperm Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41479, 1317261, 'Delphinidae', 'Oceanic Dolphins', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41480, 1317267, 'Tursiops', 'Bottlenose Dolphins', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41482, 41480, 'Tursiops truncatus', 'Common Bottlenose Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41493, 1317267, 'Stenella', 'Side-striped Dolphins', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41478, 41477, 'Eschrichtius robustus', 'Gray Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41481, 41480, 'Tursiops aduncus', 'Indo-Pacific Bottlenose Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41494, 41493, 'Stenella coeruleoalba', 'Striped Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41485, 1317267, 'Sousa', 'Humpback Dolphins', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41489, 1317267, 'Sotalia', 'Estuarine Dolphins', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41487, 41485, 'Sousa teuszii', 'Atlantic Humpback Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41496, 41493, 'Stenella longirostris', 'Spinner Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41503, 41493, 'Stenella frontalis', 'Atlantic Spotted Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41513, 1317265, 'Cephalorhynchus', 'Blunt-nosed dolphins', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41500, 41493, 'Stenella attenuata', 'Pantropical Spotted Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41515, 41513, 'Cephalorhynchus hectori', 'Hector''s Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41504, 41479, 'Lagenorhynchus', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41505, 41504, 'Lagenorhynchus albirostris', 'White-beaked Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41514, 41513, 'Cephalorhynchus commersonii', 'Commerson''s Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41516, 41513, 'Cephalorhynchus eutropia', 'Chilean Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41495, 41493, 'Stenella clymene', 'Clymene Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41524, 1317267, 'Delphinus', 'Common Dolphins', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41526, 41524, 'Delphinus delphis', 'Common Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41520, 41479, 'Orcinus', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41521, 41520, 'Orcinus orca', 'Orca', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41528, 1317266, 'Globicephala', 'Pilot Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41518, 1317266, 'Orcaella', 'Snubfin Dolphins', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41519, 41518, 'Orcaella brevirostris', 'Irrawaddy Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41517, 41513, 'Cephalorhynchus heavisidii', 'Heaviside''s Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41522, 1317267, 'Lagenodelphis', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41523, 41522, 'Lagenodelphis hosei', 'Fraser''s Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41540, 1317266, 'Grampus', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41532, 41528, 'Globicephala macrorhynchus', 'Short-finned Pilot Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41529, 41528, 'Globicephala melas', 'Long-finned Pilot Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41538, 1317266, 'Pseudorca', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41539, 41538, 'Pseudorca crassidens', 'False Killer Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41535, 1317265, 'Lissodelphis', 'Right Whale Dolphins', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41537, 41535, 'Lissodelphis borealis', 'Northern Right Whale Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41534, 41533, 'Feresa attenuata', 'Pygmy Killer Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41533, 1317266, 'Feresa', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41536, 41535, 'Lissodelphis peronii', 'Southern Right Whale Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41546, 424321, 'Balaenopteridae', 'Rorquals', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41547, 41546, 'Balaenoptera', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41550, 41547, 'Balaenoptera acutorostrata', 'Common Minke Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41541, 41540, 'Grampus griseus', 'Risso''s Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41553, 41547, 'Balaenoptera musculus', 'Blue Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41544, 1317266, 'Steno', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41545, 41544, 'Steno bredanensis', 'Rough-toothed Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41558, 41547, 'Balaenoptera edeni', 'Eden''s Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41543, 41542, 'Peponocephala electra', 'Melon-headed Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41542, 1317266, 'Peponocephala', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41565, 41546, 'Megaptera', 'Humpback Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41566, 41565, 'Megaptera novaeangliae', 'Humpback Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41562, 41547, 'Balaenoptera physalus', 'Fin Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41567, 424321, 'Balaenidae', 'Bowhead and Right Whales', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41568, 41567, 'Eubalaena', 'Right Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41571, 41568, 'Eubalaena australis', 'Southern Right Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41559, 41547, 'Balaenoptera borealis', 'Sei Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41570, 41568, 'Eubalaena glacialis', 'North Atlantic Right Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41572, 41567, 'Balaena', 'Bowhead Whales', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41569, 41568, 'Eubalaena japonica', 'North Pacific Right Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41636, 41573, 'Ursidae', 'Bears', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41687, 372843, 'Phocidae', 'Earless Seals', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41637, 846255, 'Ursus', 'Holarctic Bears', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41641, 41637, 'Ursus arctos', 'Brown Bear', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41644, 41637, 'Ursus maritimus', 'Polar Bear', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41688, 41687, 'Pusa', 'Ringed Seal and allies', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41699, 41687, 'Lobodon', 'Crabeater Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41700, 41699, 'Lobodon carcinophaga', 'Crabeater Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41701, 41687, 'Pagophilus', 'Harp Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41691, 41688, 'Pusa hispida', 'Ringed Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41707, 41687, 'Phoca', 'common seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41708, 41707, 'Phoca vitulina', 'Harbor Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41702, 41701, 'Pagophilus groenlandicus', 'Harp Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41719, 41687, 'Erignathus', 'Bearded Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41720, 41719, 'Erignathus barbatus', 'Bearded Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41714, 41707, 'Phoca largha', 'Spotted Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41715, 41687, 'Monachus', 'Mediterranean Monk Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41716, 41715, 'Monachus monachus', 'Mediterranean Monk Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41705, 41687, 'Cystophora', 'Hooded Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41706, 41705, 'Cystophora cristata', 'Hooded Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41732, 41687, 'Halichoerus', 'Grey Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41727, 41687, 'Mirounga', 'Elephant Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41728, 41727, 'Mirounga angustirostris', 'Northern Elephant Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41729, 41727, 'Mirounga leonina', 'Southern Elephant Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41730, 41687, 'Leptonychotes', 'Weddell Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41731, 41730, 'Leptonychotes weddellii', 'Weddell Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41723, 41687, 'Hydrurga', 'Leopard Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41724, 41723, 'Hydrurga leptonyx', 'Leopard Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41726, 41725, 'Ommatophoca rossii', 'Ross Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41725, 41687, 'Ommatophoca', 'Ross Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41736, 372843, 'Otariidae', 'Eared Seals', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41737, 41736, 'Zalophus', 'California, Galápagos, and Japanese Sea Lions', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41740, 41737, 'Zalophus californianus', 'California Sea Lion', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41741, 41736, 'Arctocephalus', 'Southern Fur Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41733, 41732, 'Halichoerus grypus', 'Gray Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41738, 41737, 'Zalophus wollebaeki', 'Galápagos Sea Lion', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41751, 41741, 'Arctocephalus gazella', 'Antarctic Fur Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41748, 41741, 'Arctocephalus australis', 'South American Fur Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41747, 41741, 'Arctocephalus galapagoensis', 'Galápagos Fur Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41739, 41737, 'Zalophus japonicus', 'Japanese Sea Lion', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41752, 41741, 'Arctocephalus forsteri', 'Long-nosed Fur Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41754, 41736, 'Eumetopias', 'Steller Sea Lions', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41755, 41754, 'Eumetopias jubatus', 'Steller Sea Lion', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41760, 41736, 'Otaria', 'South American Sea Lions', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41761, 41760, 'Otaria flavescens', 'South American Sea Lion', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41764, 372843, 'Odobenidae', 'Walruses', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41758, 41736, 'Neophoca', 'Australasian Sea Lions', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41759, 41758, 'Neophoca cinerea', 'Australian Sea Lion', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41756, 41736, 'Callorhinus', 'Northern Fur Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41757, 41756, 'Callorhinus ursinus', 'Northern Fur Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (43367, 848323, 'Primates', 'Primates', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (46306, 848321, 'Sirenia', 'Sirenians', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (43642, 554251, 'Pitheciidae', 'Sakis, Titis, and Uakaris', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (43643, 846203, 'Pithecia', 'Sakis', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41765, 41764, 'Odobenus', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (41766, 41765, 'Odobenus rosmarus', 'Walrus', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (46307, 46306, 'Dugongidae', 'Dugongs', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (46310, 846236, 'Dugong', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (46308, 1272846, 'Hydrodamalis', 'Sea Cows', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (46309, 46308, 'Hydrodamalis gigas', 'Steller''s Sea Cow', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47120, 1, 'Arthropoda', 'Arthropods', 'phylum');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47158, 372739, 'Insecta', 'Insects', 'class');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47157, 184884, 'Lepidoptera', 'Butterflies and Moths', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47208, 184884, 'Coleoptera', 'Beetles', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47201, 184884, 'Hymenoptera', 'Ants, Bees, Wasps, and Sawflies', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47119, 245097, 'Arachnida', 'Arachnids', 'class');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47118, 47119, 'Araneae', 'Spiders', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47115, 1, 'Mollusca', 'Mollusks', 'phylum');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47114, 47115, 'Gastropoda', 'Gastropods', 'class');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (46311, 46310, 'Dugong dugon', 'Dugong', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47224, 47157, 'Papilionoidea', 'Butterflies', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47922, 47224, 'Nymphalidae', 'Brush-footed Butterflies', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (49682, 47157, 'Pyraloidea', 'Pyralid and Crambid Snout Moths', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (48202, 702480, 'Scarabaeoidea', 'Scarabs, Stag Beetles, and Allies', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (48736, 60473, 'Curculionidae', 'True Weevils', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47866, 367176, 'Thomisidae', 'Crab Spiders', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (48289, 246139, 'Neogastropoda', NULL, 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47273, 196614, 'Elasmobranchii', 'Sharks and Rays', 'subclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (47459, 47115, 'Cephalopoda', 'Cephalopods', 'class');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (49068, 1040842, 'Balanomorpha', 'Symmetrical Sessile Barnacles', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (52002, 49682, 'Crambidae', 'Crambid Snout Moths', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (52029, 47157, 'Zygaenoidea', 'Flannel, Slug Caterpillar, Leaf Skeletonizer, and Allied Moths', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (54028, 1269342, 'Pompilidae', 'Spider Wasps', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (53635, 49068, 'Coronuloidea', NULL, 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (53657, 1472440, 'Tmarus', 'Octopus Spiders', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (50870, 551308, 'Lamniformes', 'Mackerel Sharks', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (50874, 50870, 'Lamnidae', 'Mackerel Sharks', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (54549, 3807, 'Pygoscelis antarcticus', 'Chinstrap Penguin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (50875, 50874, 'Carcharodon', 'White Sharks', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (50873, 50875, 'Carcharodon carcharias', 'Great White Shark', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (71130, 47208, 'Polyphaga', 'Water, Rove, Scarab, Long-horned, Leaf, and Snout Beetles', 'suborder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (71261, 3, 'Accipitriformes', 'Hawks, Eagles, Kites, and Allies', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (58597, 47922, 'Satyrinae', 'Satyrs, Morphos, and Allies', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (58598, 58597, 'Satyrini', 'Alpines, Arctics, Nymphs and Satyrs', 'tribe');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (60473, 372852, 'Curculionoidea', 'Snout and Bark Beetles', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (71268, 3, 'Suliformes', 'Gannets, Cormorants, and Allies', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (71296, 7251, 'Artamidae', 'Woodswallows, Butcherbirds, and Currawongs', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (67564, 3, 'Sphenisciformes', 'Penguins', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (55743, 480704, 'Conidae', 'Cone Snails', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (56715, 55743, 'Conus', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (85552, 26172, 'Sauria', 'Lizards', 'suborder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (85553, 26172, 'Serpentes', 'Snakes', 'suborder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (85493, 47120, 'Crustacea', 'Crustaceans', 'subphylum');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (84165, 52029, 'Limacodidae', 'Slug Caterpillar Moths', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (83796, 246139, 'Architaenioglossa', 'apple snails, river snails, and allies', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (84112, 776180, 'Ampullariidae', 'Apple Snails', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (84111, 1300249, 'Pomacea', 'Common Apple Snails', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (74890, 41435, 'Physeter macrocephalus', 'Sperm Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (74103, 41572, 'Balaena mysticetus', 'Bowhead Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (74104, 41547, 'Balaenoptera omurai', 'Omura''s Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (124417, 47201, 'Apocrita', 'Narrow-waisted Wasps, Ants, and Bees', 'suborder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (120474, 47118, 'Araneomorphae', 'Typical Spiders', 'suborder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (122486, 52002, 'Spilomelinae', 'Pearl Moths', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (127352, 372759, 'Decapodiformes', 'Squids and Cuttlefishes', 'superorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (130839, 372854, 'Byrrhoidea', 'Pill, Water and Toe-winged Beetles', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (117766, 41708, 'Phoca vitulina richardii', 'Pacific Harbor Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (122635, 48202, 'Trogidae', 'Keratin Beetles', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (126985, 1637735, 'Priocnemis', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (122636, 122635, 'Omorgus', 'Carcass Beetles', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (112853, 41489, 'Sotalia guianensis', 'Guyana Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (144117, 1091452, 'Thecostraca', 'Barnacles and Allies', 'subclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (132781, 54028, 'Pepsinae', NULL, 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (131236, 48460, 'Viruses', 'viruses', 'kingdom');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (147154, 41641, 'Ursus arctos arctos', 'Eurasian Brown Bear', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (147882, 41482, 'Tursiops truncatus ponticus', 'Black Sea Bottlenose Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (147641, 41526, 'Delphinus delphis ponticus', 'Black Sea Common Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (147550, 41553, 'Balaenoptera musculus brevicauda', 'Pygmy Blue Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (147551, 41553, 'Balaenoptera musculus intermedia', 'Antarctic Blue Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (147845, 41496, 'Stenella longirostris orientalis', 'Eastern Spinner Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (147579, 41515, 'Cephalorhynchus hectori maui', 'Maui''s Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (184884, 47158, 'Pterygota', 'Winged and Once-winged Insects', 'subclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (152870, 848324, 'Artiodactyla', 'Even-toed Ungulates and Cetaceans', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (196614, 355675, 'Chondrichthyes', 'Cartilaginous Fishes', 'class');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (152871, 925158, 'Cetacea', 'Cetaceans', 'infraorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (210289, 144117, 'Cirripedia', 'Barnacles', 'infraclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (202077, 58598, 'Pronophilina', NULL, 'subtribe');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (173240, 130839, 'Ptilodactylidae', 'Toe-winged Beetles', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (237465, 41766, 'Odobenus rosmarus rosmarus', 'Atlantic Walrus', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (209460, 41550, 'Balaenoptera acutorostrata acutorostrata', 'North Atlantic Minke Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (209461, 41550, 'Balaenoptera acutorostrata scammoni', 'North Pacific Minke Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (245097, 47120, 'Chelicerata', 'Chelicerates', 'subphylum');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (246139, 47114, 'Caenogastropoda', 'Caenogastropods', 'subclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (246134, 127352, 'Oegopsida', 'Pelagic Squids', 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (245417, 53635, 'Chelonibiidae', NULL, 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (248842, 1067386, 'Chelonibia', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (253938, 84111, 'Pomacea flagellata', 'Chivita Snail', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (245313, 1366569, 'Architeuthidae', 'Giant Squids', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (246411, 245313, 'Architeuthis', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (253698, 246411, 'Architeuthis dux', 'Giant Squid', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (237878, 41708, 'Phoca vitulina mellonae', 'Ungava Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (326777, 124417, 'Aculeata', 'Ants, Bees, and Stinging Wasps', 'infraorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (342614, 120474, 'Entelegynae', 'Entelegyne Spiders', 'infraorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (367176, 342614, 'Thomisoidea', 'Thomisoidea Spiders', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (371057, 85552, 'Gekkota', 'Geckos', 'infraorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (372234, 39532, 'Chelonioidea', 'Sea Turtles', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (367389, 48736, 'Dryophthorinae', NULL, 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (318988, 928021, 'Samea', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (361550, 572894, 'Araeopidius', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (361543, 361550, 'Araeopidius monachus', NULL, 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (306921, 122636, 'Omorgus monachus', NULL, 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (372739, 47120, 'Hexapoda', 'Hexapods', 'subphylum');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (372852, 71130, 'Cucujiformia', 'Cucujiform Beetles', 'infraorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (372854, 71130, 'Elateriformia', 'Elateriform Beetles', 'infraorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (372843, 41573, 'Phocoidea', 'Pinnipeds', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (424322, 152871, 'Odontoceti', 'Toothed Whales', 'parvorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (372759, 47459, 'Coleoidea', 'Octopuses, Squids, and Cuttlefishes', 'subclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (424321, 152871, 'Mysticeti', 'Baleen Whales', 'parvorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (446611, 41553, 'Balaenoptera musculus musculus', 'Northern Blue Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (432094, 56715, 'Conus monachus', 'Monastic Cone', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (413524, 3808, 'Pygoscelis papua papua', 'Northern Gentoo Penguin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (473790, 85493, 'Multicrustacea', 'Typical Crustaceans', 'superclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (464038, 210289, 'Thoracica', 'Normal Barnacles', 'subterclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (480704, 48289, 'Conoidea', 'Cone Snails and Allies', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (446639, 41687, 'Neomonachus', 'Hawaiian Monk Seals', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (446640, 446639, 'Neomonachus schauinslandi', 'Hawaiian Monk Seal', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (474974, 1633604, 'Dalcerides', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (469961, 41485, 'Sousa plumbea', 'Indian Humpback Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (446644, 41440, 'Phocoena phocoena relicta', 'Black Sea Porpoise', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (446614, 41755, 'Eumetopias jubatus monteriensis', 'Eastern Steller Sea Lion', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (446615, 41755, 'Eumetopias jubatus jubatus', 'Western Steller Sea Lion', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (508027, 367389, 'Rhynchophorini', NULL, 'tribe');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (492346, 30403, 'Hydrophiinae', 'Australian Elapids (inc. Sea Snakes)', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (483035, 126985, 'Priocnemis monachus', 'Large black hunting wasp', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (500655, 43643, 'Pithecia milleri', 'Miller''s Saki', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (508823, 41472, 'Inia geoffrensis boliviensis', 'Bolivian River Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (533484, 41691, 'Pusa hispida ladogensis', 'Lake Ladoga Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (531609, 41691, 'Pusa hispida saimensis', 'Saimaa Ringed Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (520333, 19349, 'Myiopsitta monachus luchsi', 'Cliff Parakeet', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (533493, 41691, 'Pusa hispida botnica', 'Baltic Ringed Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (508529, 19349, 'Myiopsitta monachus cotorra', 'Paraguayan Monk Parakeet', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (554251, 936377, 'Platyrrhini', 'New World Monkeys', 'parvorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (551307, 47273, 'Selachii', 'Sharks', 'infraclass');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (551308, 551307, 'Galeomorphi', 'Galean Sharks', 'superorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (566601, 41708, 'Phoca vitulina vitulina', 'Atlantic Harbor Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (575103, 41485, 'Sousa sahulensis', 'Australian Humpback Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (551436, 246139, 'Campaniloidea', NULL, 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (572894, 173240, 'Araeopidiinae', NULL, 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (541892, 474974, 'Dalcerides alba', NULL, 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (555603, 16793, 'Tyrannus savana monachus', NULL, 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (533494, 41691, 'Pusa hispida ochotensis', 'Okhotsk Ringed Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (702480, 71130, 'Scarabaeiformia', 'Scarabaeiform Beetles', 'infraorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (623433, 41440, 'Phocoena phocoena phocoena', 'Atlantic Harbor Porpoise', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (623441, 41440, 'Phocoena phocoena vomerina', 'Pacific Harbour Porpoise', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (702570, 41472, 'Inia geoffrensis geoffrensis', 'Amazon River Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (626289, 202077, 'Quilaphoetosus', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (705318, 41482, 'Tursiops truncatus gephyreus', 'Lahille''s Bottlenose Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (698251, 41529, 'Globicephala melas edwardii', 'Southern Long-finned Pilot Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (698783, 41496, 'Stenella longirostris longirostris', 'Gray’s Spinner Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (629551, 2427, 'Actenoides monachus monachus', 'Blue-headed Kingfisher', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (656915, 248842, 'Chelonibia caretta', NULL, 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (711289, 41733, 'Halichoerus grypus atlantica', 'Atlantic Grey Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (705331, 41566, 'Megaptera novaeangliae australis', 'Southern Humpback Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (705330, 41566, 'Megaptera novaeangliae novaeangliae', 'North Atlantic Humpback Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (705329, 41566, 'Megaptera novaeangliae kuzira', 'North Pacific Humpback Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (705323, 41482, 'Tursiops truncatus truncatus', 'Common Bottlenose Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (711288, 41733, 'Halichoerus grypus grypus', 'Baltic Grey Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (711285, 41720, 'Erignathus barbatus barbatus', 'Atlantic Bearded Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (709337, 3808, 'Pygoscelis papua ellsworthi', 'Southern Gentoo Penguin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (711286, 41720, 'Erignathus barbatus nauticus', 'Pacific Bearded Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (705324, 41553, 'Balaenoptera musculus indica', 'Northern Indian Blue Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (776180, 83796, 'Ampullarioidea', 'apple snails', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (726681, 19349, 'Myiopsitta monachus monachus', 'South American Monk Parakeet', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (746264, 1134336, 'Papillomaviridae', 'Warts', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (777417, 41500, 'Stenella attenuata graffmani', 'Coastal Spotted Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (778492, 41526, 'Delphinus delphis delphis', NULL, 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (778491, 41562, 'Balaenoptera physalus physalus', 'Northern Fin Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (728236, 12329, 'Philemon corniculatus monachus', 'Southern Noisy Friarbird', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (711292, 41691, 'Pusa hispida hispida', 'Arctic Ringed Seal', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (777415, 41500, 'Stenella attenuata attenuata', 'offshore pantropical spotted dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (778490, 41559, 'Balaenoptera borealis schlegelii', 'Southern Sei Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (786045, 43367, 'Haplorhini', 'Monkeys, Apes, and Tarsiers', 'suborder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (797541, 39657, 'Carettinae', 'Hawksbill, Loggerhead, and Ridley Sea Turtles', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (783080, 746264, 'Firstpapillomavirinae', 'Terrestrial Vertebrate Papillomaviruses', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (801536, 551436, 'Plesiotrochidae', NULL, 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (785322, 1100884, 'Eugnoristus', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (785321, 785322, 'Eugnoristus monachus', NULL, 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (780509, 41562, 'Balaenoptera physalus quoyi', 'Southern Fin Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (781408, 41559, 'Balaenoptera borealis borealis', 'Northern Sei Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (783107, 783080, 'Dyozetapapillomavirus', 'ζ2 Testudine Papillomaviruses', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (825120, 53657, 'Tmarus caretta', NULL, 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (848323, 848320, 'Euarchontoglires', 'Primates, Rodents, and Allies', 'superorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (925158, 152870, 'Whippomorpha', 'Cetaceans and Hippopotamuses', 'suborder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (846255, 41636, 'Ursinae', 'Typical Bears', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (848321, 848320, 'Afrotheria', 'Afromammals', 'superorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (846203, 43642, 'Pitheciinae', 'Sakis and Uakaris', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (846236, 46307, 'Dugonginae', 'Dugongs', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (846059, 1317260, 'Pontoporiidae', 'Estuarine River Dolphins', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (846055, 1317258, 'Kogiidae', 'Dwarf and Pygmy Sperm Whales', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (852369, 43643, 'Pithecia monachus', 'Monk Saki', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (850967, 41402, 'Mesoplodon hotaula', 'Deraniyagala''s Beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (980017, 7251, 'Tyrannidae', 'Tyrant Flycatchers', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (936377, 786045, 'Simiiformes', 'Monkeys and Apes', 'infraorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (928021, 122486, 'Nomophilini', NULL, 'tribe');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1040842, 464038, 'Thoracicalcarea', 'Thoracican Barnacles', 'superorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (980192, 7251, 'Leiothrichidae', 'Laughingthrushes and Allies', 'family');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (970572, 41766, 'Odobenus rosmarus divergens', 'Pacific Walrus', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1052880, 41515, 'Cephalorhynchus hectori hectori', 'Hector''s Dolphin (Hector''s)', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (963168, 41529, 'Globicephala melas melas', 'Northern Long-finned Pilot Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1045501, 626289, 'Quilaphoetosus monachus', NULL, 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1063781, 318988, 'Samea carettalis', NULL, 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1091452, 473790, 'Hexanauplia', 'Barnacles and Copepods', 'class');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1100884, 508027, 'Litosomina', NULL, 'subtribe');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1067386, 245417, 'Chelonibiinae', NULL, 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1134331, 131236, 'Cossaviricota', NULL, 'phylum');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1134333, 1134331, 'Papovaviricetes', NULL, 'class');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1134336, 1134333, 'Zurhausenvirales', NULL, 'order');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1118474, 801536, 'Plesiotrochus', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1149437, 1118474, 'Plesiotrochus monachus', NULL, 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1127950, 35099, 'Suta monachus', 'Inland Hooded Snake', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1155858, 41424, 'Berardius minimus', 'Least Beaked Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1269342, 326777, 'Pompiloidea', 'Spider Wasps, Velvet Ants, and Allies', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1300249, 84112, 'Pomaceinae', NULL, 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1289299, 980192, 'Pterorhinus', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1289331, 4262, 'Leucocarbo', 'Blue-eyed Shags and allies', 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1289402, 1289299, 'Pterorhinus chinensis', 'Black-throated Laughingthrush', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1289590, 1289331, 'Leucocarbo bransfieldensis', 'Antarctic Shag', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1306016, 41446, 'Phocoenoides dalli dalli', 'Dall''s Porpoise', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1289817, 1289402, 'Pterorhinus chinensis monachus', 'Black-throated Laughingthrush (Hainan)', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1272846, 46307, 'Hydrodamalinae', 'Steller''s Sea Cows', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1306017, 41446, 'Phocoenoides dalli truei', 'True''s Porpoise', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1317261, 424322, 'Delphinoidea', 'Oceanic Dolphins and Porpoises', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1317267, 41479, 'Delphininae', 'Long-nosed Dolphins', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1317266, 41479, 'Globicephalinae', 'Pilot Whales and allies', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1317265, 41479, 'Lissodelphininae', 'Right Whale Dolphins and allies', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1317258, 424322, 'Physeteroidea', 'Sperm Whales', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1317295, 1317265, 'Sagmatias', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1317260, 424322, 'Inioidea', 'American River Dolphins', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1317256, 424322, 'Ziphioidea', 'Beaked Whales', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1365377, 3808, 'Pygoscelis papua taeniata', 'eastern gentoo penguin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1365378, 3808, 'Pygoscelis papua poncetii', 'South Georgian Gentoo Penguin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1366913, 39657, 'Cheloniinae', 'Green and Flatback Sea Turtles', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1368491, 1317295, 'Sagmatias obliquidens', 'Pacific White-sided Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1368492, 1317295, 'Sagmatias obscurus', 'Dusky Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1368482, 41479, 'Leucopleurus', NULL, 'genus');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1368483, 1368482, 'Leucopleurus acutus', 'Atlantic White-sided Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1368489, 1317295, 'Sagmatias australis', 'Peale''s Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1408504, 41526, 'Delphinus delphis bairdii', 'Eastern Pacific Long-beaked Common Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1368490, 1317295, 'Sagmatias cruciger', 'Hourglass Dolphin', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1366569, 246134, 'Architeuthoidea', 'Giant Squids and Neosquids', 'superfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1408503, 41526, 'Delphinus delphis tropicalis', 'Indo-Pacific Common Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1472437, 47866, 'Thomisinae', NULL, 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1541533, 5067, 'Aegypiinae', 'Typical Old World Vultures', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1541352, 1627, 'Centropodinae', 'Coucals', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1472440, 1472437, 'Tmarini', NULL, 'tribe');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1453916, 41547, 'Balaenoptera brydei', 'Bryde''s Whale', 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1435993, 41496, 'Stenella longirostris centroamericana', 'Central American Spinner Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1500452, 41547, 'Balaenoptera musculus × physalus', 'Blue × Fin Whale', 'hybrid');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1471381, 1471382, 'Dyozetapapillomavirus one cmpv-i', 'Green Sea Turtle Papillomavirus 1', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1471382, 783107, 'Dyozetapapillomavirus one', NULL, 'species');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1471380, 1471382, 'Dyozetapapillomavirus one ccpv-i', 'Loggerhead Sea Turtle Papillomavirus 1', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1563907, 85552, 'Iguania', NULL, 'infraorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1567778, 1563907, 'Acrodonta', NULL, 'parvorder');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1542375, 2314, 'Halcyoninae', 'Tree Kingfishers', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1633602, 84165, 'Dalcerinae', 'Jewel Caterpillar Moths', 'subfamily');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1633604, 1633602, 'Acragini', NULL, 'tribe');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1602533, 41521, 'Orcinus orca rectipinnus', 'Bigg''s Killer Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1602531, 41521, 'Orcinus orca ater', 'Resident Killer Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1621825, 41514, 'Cephalorhynchus commersonii commersonii', NULL, 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1621824, 41514, 'Cephalorhynchus commersonii kerguelenensis', 'Kerguelen Dolphin', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1602532, 41521, 'Orcinus orca orca', 'Common Killer Whale', 'subspecies');
INSERT INTO inaturalist.taxa (id, parent_id, scientific_name, vernacular_name, rank) VALUES (1637735, 132781, 'Priocnemini', NULL, 'tribe');
