-- Phase 1: Bigg's killer whale catalog — schema only.
--
-- An authoritative catalog of individual whales and their social groups
-- (matrilines/pods), plus the naming provenance (designations, nicknames,
-- naming parties). Seeded OUT OF BAND by scripts/seed/seed-biggs.ts from
-- data/biggs-ids.tsv (NOT in this migration): prod gets an empty schema here
-- via `supabase db push`, then the seed script is run once against the pooler.
--
-- Access control per the reference-table precedent (20260619184037): every
-- table is PostgREST-exposed `public`, so ENABLE RLS + a permissive SELECT
-- policy for anon/authenticated ship in THIS migration (RLS defaults otherwise
-- silently zero out reads/joins).
--
-- All enum values below are LOCKED: PostgreSQL has no ALTER TYPE ... DROP VALUE,
-- so an unwanted value would need a destructive migration to remove.

-- ============================================================================
-- enums
-- ============================================================================
CREATE TYPE public.life_status AS ENUM
  ('alive', 'deceased', 'presumed_deceased', 'unknown');

CREATE TYPE public.parentage_certainty AS ENUM
  ('confirmed', 'presumed', 'hypothesized');

CREATE TYPE public.social_group_kind AS ENUM
  ('ecotype', 'clan', 'pod', 'matriline', 'named_group');

CREATE TYPE public.membership_basis AS ENUM
  ('maternal', 'association', 'curated');

CREATE TYPE public.designation_scheme AS ENUM
  ('bc_wa', 'alaska', 'california', 'other');

CREATE TYPE public.designation_status AS ENUM
  ('active', 'superseded', 'uncertain');

CREATE TYPE public.party_kind AS ENUM
  ('researcher', 'organization', 'agency', 'community_project', 'first_nation');

CREATE TYPE public.nickname_status AS ENUM
  ('official', 'provisional', 'proposed', 'deprecated', 'awaiting_decision');

-- Reuses the existing public.sex ('male','female') from 20250903172708_initial_schema.sql
-- (nullable columns below carry "unknown").

-- ============================================================================
-- parties — cataloguers & namers (people, orgs, community projects)
-- Reused by designations.authority_id and nicknames.namer_id. `name` is the
-- natural key the seed upserts on. `kind` nullable: the "Who Nicknamed" source
-- mixes people/orgs/agencies with no clean signal (cf. collections.kind).
-- ============================================================================
CREATE TABLE public.parties (
  id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL UNIQUE,
  kind public.party_kind,
  url  TEXT
);
ALTER TABLE public.parties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Parties are publicly readable"
  ON public.parties FOR SELECT TO anon, authenticated USING (true);

-- ============================================================================
-- individuals — the stable biological animal (identity survives renamings)
-- primary_designation is the local BC/WA T-code; UNIQUE + NOT NULL, doubles as
-- the seed's natural key. Birth is a year range: ≤1961 -> (null,1961),
-- <1968 -> (null,1967), 1979 -> (1979,1979), UNK -> (null,null).
-- Self-FKs (mother_id/father_id) are nullable and filled by the seed's pass 2.
-- taxon_id defaults to Orcinus orca (41521, seeded in 20250910212502_taxa.sql);
-- an FK to a non-public schema needs no grant (only PostgREST embeds would).
-- ============================================================================
CREATE TABLE public.individuals (
  id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  primary_designation TEXT NOT NULL UNIQUE,
  taxon_id            INTEGER NOT NULL DEFAULT 41521 REFERENCES inaturalist.taxa (id),
  sex                 public.sex,
  born_earliest       INTEGER,
  born_latest         INTEGER,
  life_status         public.life_status NOT NULL DEFAULT 'unknown',
  mother_id           INTEGER REFERENCES public.individuals (id),
  maternity_certainty public.parentage_certainty NOT NULL DEFAULT 'presumed',
  father_id           INTEGER REFERENCES public.individuals (id),
  paternity_certainty public.parentage_certainty,
  notes               TEXT
);
CREATE INDEX ON public.individuals (taxon_id);
CREATE INDEX ON public.individuals (mother_id);
CREATE INDEX ON public.individuals (father_id);
ALTER TABLE public.individuals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Individuals are publicly readable"
  ON public.individuals FOR SELECT TO anon, authenticated USING (true);

-- ============================================================================
-- social_groups — matrilines, pods, clans, ecotypes, named gangs
-- The matriarch link lives HERE (anchor_individual_id), not on individuals, so
-- there is no table-level cycle. designation (e.g. 'T065') is UNIQUE and the
-- seed's natural key for matrilines; null for named_group/ecotype.
-- ============================================================================
CREATE TABLE public.social_groups (
  id                   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  kind                 public.social_group_kind NOT NULL,
  anchor_individual_id INTEGER REFERENCES public.individuals (id),
  designation          TEXT UNIQUE,
  parent_group_id      INTEGER REFERENCES public.social_groups (id),
  notes                TEXT
);
CREATE INDEX ON public.social_groups (anchor_individual_id);
CREATE INDEX ON public.social_groups (parent_group_id);
ALTER TABLE public.social_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Social groups are publicly readable"
  ON public.social_groups FOR SELECT TO anon, authenticated USING (true);

-- ============================================================================
-- designations — formal catalog codes, one animal may carry many
-- code (e.g. 'T065A5','AM25','CA20') is UNIQUE and the seed's natural key.
-- Codes are stored AS WRITTEN (zero-padded); the future sightings bridge will
-- normalize (strip padding) at match time — not built here.
-- superseded_by handles renamings (e.g. T46A -> T122), filled by seed pass 2.
-- in_catalog=false captures "Not in the Catalogue" / "Not on Finwave".
-- ============================================================================
CREATE TABLE public.designations (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  individual_id INTEGER NOT NULL REFERENCES public.individuals (id),
  authority_id  INTEGER REFERENCES public.parties (id),
  code          TEXT NOT NULL UNIQUE,
  scheme        public.designation_scheme NOT NULL,
  is_primary    BOOLEAN NOT NULL DEFAULT false,
  status        public.designation_status NOT NULL DEFAULT 'active',
  superseded_by INTEGER REFERENCES public.designations (id),
  in_catalog    BOOLEAN NOT NULL DEFAULT true
);
CREATE INDEX ON public.designations (individual_id);
CREATE INDEX ON public.designations (authority_id);
CREATE INDEX ON public.designations (superseded_by);
ALTER TABLE public.designations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Designations are publicly readable"
  ON public.designations FOR SELECT TO anon, authenticated USING (true);

-- ============================================================================
-- group_memberships — temporal membership (Bigg's disperse)
-- ============================================================================
CREATE TABLE public.group_memberships (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id      INTEGER NOT NULL REFERENCES public.social_groups (id),
  individual_id INTEGER NOT NULL REFERENCES public.individuals (id),
  joined_year   INTEGER,
  left_year     INTEGER,
  is_current    BOOLEAN NOT NULL DEFAULT true,
  basis         public.membership_basis NOT NULL DEFAULT 'maternal',
  CONSTRAINT group_membership_unique UNIQUE (group_id, individual_id)
);
CREATE INDEX ON public.group_memberships (group_id);
CREATE INDEX ON public.group_memberships (individual_id);
ALTER TABLE public.group_memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Group memberships are publicly readable"
  ON public.group_memberships FOR SELECT TO anon, authenticated USING (true);

-- ============================================================================
-- nicknames — the cultural naming layer; targets an individual XOR a group
-- (collective names like "Motley Crew" attach to a group). UNIQUE per target+name
-- keeps the seed idempotent.
-- ============================================================================
CREATE TABLE public.nicknames (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  individual_id   INTEGER REFERENCES public.individuals (id),
  social_group_id INTEGER REFERENCES public.social_groups (id),
  name            TEXT NOT NULL,
  story           TEXT,
  namer_id        INTEGER REFERENCES public.parties (id),
  theme           TEXT,
  status          public.nickname_status NOT NULL DEFAULT 'official',
  named_year      INTEGER,
  CONSTRAINT nickname_target_ck CHECK (num_nonnulls(individual_id, social_group_id) = 1),
  CONSTRAINT nickname_individual_name_unique UNIQUE (individual_id, name),
  CONSTRAINT nickname_group_name_unique UNIQUE (social_group_id, name)
);
CREATE INDEX ON public.nicknames (individual_id);
CREATE INDEX ON public.nicknames (social_group_id);
CREATE INDEX ON public.nicknames (namer_id);
ALTER TABLE public.nicknames ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Nicknames are publicly readable"
  ON public.nicknames FOR SELECT TO anon, authenticated USING (true);
