-- =====================================================================
-- recordedByID — emit contributor ORCIDs in the DarwinCore export
--
-- public.contributors.orcid has existed since 20260619184037 and the iNat
-- capture (20260621010000) populates it in canonical URI form, but nothing
-- ever read it: the archive emits recordedBy (a name) and no identifier.
-- PRODUCT.md claimed otherwise ("recordedByID emit shipped in v1.3"); it had
-- not, and this migration is what makes that sentence true.
--
-- Two changes:
--   1. A format CHECK on public.contributors.orcid, so a malformed value
--      cannot reach a published archive.
--   2. recordedByID as occurrence column 26 (0-indexed) in both source views
--      and the UNION — from the joined contributor (native), NULL (Maplify).
--
-- The column is APPENDED, never inserted. scripts/dwca/fields.ts documents
-- the ordinal invariant: the array index is simultaneously the TSV column
-- ordinal and the meta.xml field index, and these views' SELECT order is
-- pinned to it. Inserting recordedByID beside recordedBy (where it reads
-- better) would silently renumber seven fields of a published archive.
--
-- Both view bodies below are the live 20260621000000 definitions verbatim,
-- generated by splicing rather than retyped, with only the trailing column
-- added. CREATE OR REPLACE accepts that: Postgres permits appending columns
-- to a view, and dwc.occurrences keeps working until it is replaced in 3.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. ORCID format constraint
--
-- Canonical form is the full https URI — what the iNat v2 API returns and
-- what DwC recordedByID publishes. The final character may be 'X': ORCIDs
-- carry an ISO 7064 MOD 11-2 check digit, and 10 is written X. The checksum
-- itself is not verified; a regex cannot, and a plpgsql CHECK is more
-- machinery than a curator-entry path warrants.
--
-- NOT VALID deliberately: it enforces every future write while leaving the
-- ~3,000 existing iNat-sourced rows unaudited. They arrive pre-formatted
-- from the API and should all pass, but "should" is not "did", and a failed
-- constraint would fail the deploy that carries it (the deploy job runs
-- supabase db push before the frontend flips). Validating them is separate,
-- reversible work — tracked in beads.
-- ---------------------------------------------------------------------
ALTER TABLE public.contributors
  DROP CONSTRAINT IF EXISTS contributors_orcid_is_canonical_uri;

ALTER TABLE public.contributors
  ADD CONSTRAINT contributors_orcid_is_canonical_uri
  CHECK (orcid IS NULL OR orcid ~ '^https://orcid\.org/[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$')
  NOT VALID;

COMMENT ON CONSTRAINT contributors_orcid_is_canonical_uri ON public.contributors IS
  'ORCID stored as the full https://orcid.org/XXXX-XXXX-XXXX-XXXX URI - the form the iNat v2 API returns and the form DwC recordedByID publishes. Trailing X is the ISO 7064 MOD 11-2 check digit written as 10. NOT VALID: enforces new writes only; pre-existing rows unaudited.';

-- ---------------------------------------------------------------------
-- 2a. dwc._native_occurrences - append recordedByID.
--     The view already joins public.contributors AS c for recordedBy
--     (col 18), so no new join is needed. NULL is the common case and is
--     correct: an identifier we do not hold is absent, never inferred.
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW dwc._native_occurrences AS
SELECT
  -- 0. occurrenceID (ALIGN-02, ALIGN-06)
  ('salishsea:' || o.id::text)::text                                            AS "occurrenceID",
  -- 1. basisOfRecord (ALIGN-02 / POLICY §3.1)
  'HumanObservation'::text                                                      AS "basisOfRecord",
  -- 2. eventDate (ALIGN-02, ALIGN-05) — full ISO-8601 UTC with Z suffix.
  to_char(o.observed_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')::text AS "eventDate",
  -- 3. scientificName (ALIGN-02, ALIGN-03)
  tc.scientific_name::text                                                      AS "scientificName",
  -- 4. taxonRank (ALIGN-03)
  tc.taxon_rank::text                                                           AS "taxonRank",
  -- 5-10. kingdom..genus (ALIGN-03)
  tc.kingdom::text                                                              AS "kingdom",
  tc.phylum::text                                                               AS "phylum",
  tc.class::text                                                                AS "class",
  tc.order_::text                                                               AS "order",
  tc.family::text                                                               AS "family",
  tc.genus::text                                                                AS "genus",
  -- 11. decimalLatitude (ALIGN-04)
  gis.ST_Y(o.subject_location::gis.geometry)::double precision                  AS "decimalLatitude",
  -- 12. decimalLongitude (ALIGN-04)
  gis.ST_X(o.subject_location::gis.geometry)::double precision                  AS "decimalLongitude",
  -- 13. geodeticDatum (ALIGN-04)
  'WGS84'::text                                                                 AS "geodeticDatum",
  -- 14. coordinateUncertaintyInMeters (ALIGN-04)
  NULLIF(o.accuracy, 0)::integer                                                AS "coordinateUncertaintyInMeters",
  -- 15. individualCount
  o.count::integer                                                              AS "individualCount",
  -- 16. occurrenceStatus
  'present'::text                                                               AS "occurrenceStatus",
  -- 17. occurrenceRemarks
  NULLIF(TRIM(regexp_replace(o.body, '<[^>]+>', '', 'g')), '')::text             AS "occurrenceRemarks",
  -- 18. recordedBy (D-09 / POLICY §2.1) — contributor name (unchanged)
  c.name::text                                                                  AS "recordedBy",
  -- 19. institutionCode (NEW — D-01 / ATTR-01)
  'SalishSea'::text                                                             AS "institutionCode",
  -- 20. rightsHolder (D-01 / ATTR-01) — CONSTANT (was c.name)
  'SalishSea.io'::text                                                          AS "rightsHolder",
  -- 21. datasetName (D-04 / ATTR-02) — per-collection via FK join
  ('SalishSea.io — ' || c_coll.name)::text                                      AS "datasetName",
  -- 22. datasetID (D-17 / POLICY §6.3) — unchanged
  'https://salishsea.io/datasets/occurrences-v1'::text                          AS "datasetID",
  -- 23. license (D-20 / POLICY §1.1) — CC-BY-NC 4.0
  'https://creativecommons.org/licenses/by-nc/4.0/legalcode'::text              AS "license",
  -- 24. dynamicProperties (POLICY §2.3 + §2.4)
  NULLIF(jsonb_strip_nulls(jsonb_build_object('travelDirection', o.direction::text, 'unvalidatedIdentifiers', NULLIF(public.extract_identifiers(o.body), ARRAY[]::varchar[])))::text, '{}'::text) AS "dynamicProperties",
  -- 25. informationWithheld
  NULL::text                                                                    AS "informationWithheld",
  -- 26. recordedByID (NEW) — the observer's ORCID when we hold one.
  c.orcid::text                                                                 AS "recordedByID"
FROM public.observations o
JOIN public.contributors c        ON c.id = o.contributor_id
JOIN dwc.taxa_classification tc   ON tc.taxon_id = o.taxon_id
JOIN public.collections c_coll    ON c_coll.id = o.collection_id;
COMMENT ON VIEW dwc._native_occurrences IS '27-col native occurrence view. institutionCode=SalishSea (col 19), rightsHolder=SalishSea.io (col 20), datasetName per-collection FK (col 21), recordedByID from contributors.orcid (col 26, appended). Internal - Phase 6 reads dwc.occurrences (the UNION).';

-- ---------------------------------------------------------------------
-- 2b. dwc._maplify_occurrences - append recordedByID as a typed NULL.
--     Maplify has no contributor row to join: recordedBy is a regex over
--     the comments headline (D-02 / ATTR-01), which yields a name and
--     nothing else. There is no identifier to emit and none may be
--     inferred from a name, so the column holds its ordinal and is NULL.
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW dwc._maplify_occurrences AS
SELECT
  -- 0. occurrenceID (ALIGN-02, ALIGN-06)
  ('maplify:' || s.id::text)::text                                              AS "occurrenceID",
  -- 1. basisOfRecord (ALIGN-02 / POLICY §3.2)
  'HumanObservation'::text                                                      AS "basisOfRecord",
  -- 2. eventDate (ALIGN-02, ALIGN-05) — date-precision only per POLICY §3.2
  ((s.created_at AT TIME ZONE 'GMT')::date)::text                               AS "eventDate",
  -- 3. scientificName (ALIGN-02, ALIGN-03)
  tc.scientific_name::text                                                      AS "scientificName",
  -- 4. taxonRank (ALIGN-03)
  tc.taxon_rank::text                                                           AS "taxonRank",
  -- 5-10. kingdom..genus (ALIGN-03)
  tc.kingdom::text                                                              AS "kingdom",
  tc.phylum::text                                                               AS "phylum",
  tc.class::text                                                                AS "class",
  tc.order_::text                                                               AS "order",
  tc.family::text                                                               AS "family",
  tc.genus::text                                                                AS "genus",
  -- 11. decimalLatitude (ALIGN-04)
  gis.ST_Y(s.location::gis.geometry)::double precision                          AS "decimalLatitude",
  -- 12. decimalLongitude (ALIGN-04)
  gis.ST_X(s.location::gis.geometry)::double precision                          AS "decimalLongitude",
  -- 13. geodeticDatum (ALIGN-04)
  'WGS84'::text                                                                 AS "geodeticDatum",
  -- 14. coordinateUncertaintyInMeters (POLICY §3.2 gap — no source column)
  NULL::integer                                                                 AS "coordinateUncertaintyInMeters",
  -- 15. individualCount
  s.number_sighted::integer                                                     AS "individualCount",
  -- 16. occurrenceStatus
  'present'::text                                                               AS "occurrenceStatus",
  -- 17. occurrenceRemarks — strip HTML tags from comments
  NULLIF(TRIM(regexp_replace(s.comments, '<[^>]+>', '', 'g')), '')::text         AS "occurrenceRemarks",
  -- 18. recordedBy (D-02 / ATTR-01) — view-time regex over comments headline.
  --   Extracts the parenthetical observer name from the bracket-tag pattern:
  --   [Collection Tag] Description text (Observer Name)<br>...
  --   Guards (Wave-1 census validated — 12-01):
  --     ~ '[,]'     → NULL (multi-name comma list — 353 prod rows)
  --     ~ '^IDs?\s' → NULL (identification credit — 82 prod rows)
  --   Rows without bracket tag or parenthetical → regexp_match returns NULL → NULL.
  NULLIF(
    (CASE
      WHEN (regexp_match(split_part(s.comments, '<br>', 1),
                         '^\[[^\]]+\]\s+.+?\(([^()]+)\)'))[1] ~ '[,]'
        OR (regexp_match(split_part(s.comments, '<br>', 1),
                         '^\[[^\]]+\]\s+.+?\(([^()]+)\)'))[1] ~ '^IDs?\s'
      THEN NULL
      ELSE (regexp_match(split_part(s.comments, '<br>', 1),
                         '^\[[^\]]+\]\s+.+?\(([^()]+)\)'))[1]
    END)::text,
    NULL
  )                                                                              AS "recordedBy",
  -- 19. institutionCode (NEW — D-01 / ATTR-01)
  'SalishSea'::text                                                             AS "institutionCode",
  -- 20. rightsHolder (D-01 / ATTR-01) — CONSTANT (was dn.display_name)
  'SalishSea.io'::text                                                          AS "rightsHolder",
  -- 21. datasetName (D-04/D-06 / ATTR-02) — per-collection FK + COALESCE fallback
  ('SalishSea.io — ' || COALESCE(c_coll.name, 'Whale Alert (Global)'))::text   AS "datasetName",
  -- 22. datasetID (D-17 / POLICY §6.3) — unchanged
  'https://salishsea.io/datasets/occurrences-v1'::text                          AS "datasetID",
  -- 23. license (D-20 / POLICY §1.1) — CC-BY 4.0 (Maplify / Acartia)
  'https://creativecommons.org/licenses/by/4.0/legalcode'::text                 AS "license",
  -- 24. dynamicProperties (POLICY §2.3) — aggregatorSource now from collection name
  NULLIF(jsonb_strip_nulls(jsonb_build_object(
    'travelDirection',        public.extract_travel_direction(s.comments)::text,
    'aggregatorSource',       COALESCE(c_coll.name, 'Whale Alert (Global)'),
    'aggregatorChain',        'Whale Alert / Maplify (WASEAK) > ' || COALESCE(c_coll.name, 'Whale Alert (Global)'),
    'unvalidatedIdentifiers', NULLIF(public.extract_identifiers(s.comments), ARRAY[]::varchar[])
  ))::text, '{}'::text)                                                         AS "dynamicProperties",
  -- 25. informationWithheld
  NULL::text                                                                    AS "informationWithheld",
  -- 26. recordedByID (NEW) — no contributor row to join; see header note.
  NULL::text                                                                    AS "recordedByID"
FROM maplify.sightings s
JOIN dwc.taxa_classification tc ON tc.taxon_id = s.taxon_id
-- LEFT JOIN required: s.collection_id can be NULL (FARPB rows, unresolved trusted rows)
LEFT JOIN public.collections c_coll ON c_coll.id = s.collection_id
-- D-05: trusted-only export; D-13: number_sighted bounds; POLICY §5.3: rwsas filter
WHERE NOT s.is_test
  AND s.number_sighted BETWEEN 1 AND 1000
  AND s.source != 'rwsas'
  AND s.trusted;
COMMENT ON VIEW dwc._maplify_occurrences IS 'Phase 12 rebuild + recordedByID: 27-col Maplify occurrence view. recordedBy via regex over comments (Wave-1 census), institutionCode=SalishSea (col 19), rightsHolder=SalishSea.io (col 20), datasetName per-collection FK+COALESCE (col 21), recordedByID always NULL (col 26 - no contributor row), trusted-only (D-05). Internal - Phase 6 reads dwc.occurrences (the UNION).';

-- ---------------------------------------------------------------------
-- 3. dwc.occurrences - re-expand the UNION.
--
-- It was written as SELECT *, but Postgres expands * at definition time, so
-- the view is frozen at its original 26 columns and does NOT inherit the new
-- one. Replacing it re-expands both sides.
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW dwc.occurrences AS
SELECT * FROM dwc._native_occurrences
UNION ALL
SELECT * FROM dwc._maplify_occurrences;

COMMENT ON VIEW dwc.occurrences IS 'Encodes 04-POLICY 3.1 (native) and 3.2 (Maplify) via M-02 UNION ALL of dwc._native_occurrences and dwc._maplify_occurrences. 27 columns as of recordedByID. Read by Phase 6 (DuckDB ATTACH + COPY to CSV/GeoParquet).';
