CREATE EXTENSION citext;

CREATE DOMAIN public.email AS public.citext
	CONSTRAINT email_check CHECK ((VALUE OPERATOR(public.~) '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'::public.citext));

CREATE TABLE contributors (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  entity_id uuid NOT NULL DEFAULT gen_random_uuid(),
  "name" VARCHAR(100) NOT NULL,
  picture VARCHAR(1000)
);
ALTER TABLE public.contributors ENABLE ROW LEVEL SECURITY;

CREATE TABLE contributor_email_addresses (
  contributor_id INTEGER NOT NULL REFERENCES public.contributors (id),
  email_address public.email NOT NULL UNIQUE
);
ALTER TABLE public.contributor_email_addresses ENABLE ROW LEVEL SECURITY;

CREATE TABLE user_contributor (
  user_uuid uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  contributor_id INTEGER NOT NULL REFERENCES public.contributors (id) ON DELETE CASCADE
);
ALTER TABLE public.user_contributor ENABLE ROW LEVEL SECURITY;

CREATE FUNCTION public.create_contributor_on_sign_in() RETURNS TRIGGER AS $$
DECLARE
  v_contributor_id INTEGER;
BEGIN
  SELECT contributor_id INTO v_contributor_id
    FROM public.contributor_email_addresses
    WHERE email_address=NEW.email AND NEW.email_verified_at;
  IF NOT FOUND THEN
    INSERT INTO public.contributors ("name", "picture")
      VALUES (
        COALESCE(NEW.raw_user_meta_data->>'name', NEW.raw_user_meta_data->>'user_name', 'Anonymous'),
        NEW.raw_user_meta_data->>'picture'
      )
      RETURNING id INTO v_contributor_id;
    IF NEW.email_verified_at THEN
      INSERT INTO public.contributor_email_addresses (contributor_id, email_address)
        VALUES (v_contributor_id, NEW.raw_user_meta_data->>'email');
    END IF;
  END IF;
  INSERT INTO public.user_contributor (user_uuid, contributor_id)
    VALUES (NEW.id, v_contributor_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path='';

CREATE trigger create_contributor_on_sign_in
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE PROCEDURE public.create_contributor_on_sign_in();

DO LANGUAGE plpgsql $$
DECLARE
  r record;
  v_contributor_id integer;
BEGIN
  FOR r IN SELECT id, email, email_verified_at, raw_user_meta_data AS md FROM auth.users LOOP
    INSERT INTO public.contributors ("name", "picture")
      VALUES (COALESCE(r.md->>'name', r.md->>'user_name', 'Anonymous'), r.md->>'picture')
      RETURNING id INTO v_contributor_id;
    INSERT INTO public.user_contributor (user_uuid, contributor_id)
      VALUES (r.id, v_contributor_id);
    IF r.email_verified_at THEN
      INSERT INTO public.contributor_email_addresses (contributor_id, email_address)
        VALUES (v_contributor_id, r.email);
    END IF;
  END LOOP;
END;
$$;

DROP TABLE profiles;