-- Phase 11: Resolution Schema
-- Implements RESOLVE-02, RESOLVE-04 from .planning/REQUIREMENTS.md.
--
-- Creates the Maplify collection-resolution dictionary table + resolver function,
-- migration-resolved collection_id DEFAULTs on the three single-collection tables,
-- the inat_login dedup column on public.contributors, and the SECURITY DEFINER
-- mint_contributor helper for iNat contributor creation.
--
-- Intentional deviations:
--   D-09: SC#1 regex tightened to ^\[[^\]]+\] (non-empty bracket tags only);
--         empty/[NULL] brackets stay NULL. Documented and flagged for gsd-verifier.
--   D-05: collection_id DEFAULTs resolved at migration time via DO $$ EXECUTE format()
--         pattern — mirrors Phase 10 provider_id DEFAULT, no subquery in DEFAULT.
--   D-15: public.contributors.inat_login TEXT UNIQUE — nullable; existing native
--         rows leave inat_login NULL; iNat rows populated by mint_contributor.
--   D-16: inaturalist.mint_contributor SECURITY DEFINER + SET search_path = '' —
--         required because public.contributors has RLS enabled with no INSERT policy
--         for the postgres (pg_cron) role (mirrors create_contributor_on_sign_in).
--
-- NOTE: Acronym real-name expansions (D-10 name/org/kind UPDATE) are DEFERRED.
--   The operator confirmed at 11-02 sign-off that slug mapping is sufficient for
--   the collection_rule seed; actual organization name expansions are unknown.
--   Stub collection names remain the uppercase acronym (PSWS, MCW, etc.).
--
-- This migration is SCHEMA-ONLY. Backfill UPDATEs and ingest function edits
-- live in plan 11-04 (must follow this migration per RESEARCH Pitfall 3).
--
-- ASSUMPTIONS / EXCLUSIONS (from maplify_census.tsv, operator-confirmed 2026-06-19):
--   STAY_NULL: source 'FARPB' (384 rows) — expansion unknown; intentionally unresolved.
--   DROP:      source 'wras'  (50 rows)  — records should not exist; plan 11-04 adds
--              a one-time guarded DELETE + ingest filter on ingestion.

-- =====================================================================
-- 1. maplify.collection_rule — the DB-side resolution dictionary (D-03)
--    match_kind IN ('bracket','attribution','source') — locked precedence order
--    match_value TEXT NOT NULL — exact bracket tag text, attribution phrase, or source code
--    collection_id FK → public.collections(id) — enforced at seed time
-- =====================================================================
CREATE TABLE maplify.collection_rule (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  match_kind    TEXT    NOT NULL CHECK (match_kind IN ('bracket', 'attribution', 'source')),
  match_value   TEXT    NOT NULL,
  collection_id INTEGER NOT NULL REFERENCES public.collections(id),
  UNIQUE (match_kind, match_value)
);

-- =====================================================================
-- 2. maplify.resolve_collection — thin precedence resolver (D-02, D-03, D-04)
--    Locked precedence: bracket tag → attribution → source code → NULL
--    STABLE: reads collection_rule table; no writes; callable inside INSERT...SELECT
--    Regex ^\[([^\]]+)\] requires non-empty bracket content (D-09 tightening)
-- =====================================================================
CREATE FUNCTION maplify.resolve_collection(
  comments text,
  source   text
) RETURNS integer LANGUAGE SQL STABLE AS $$
  -- Precedence 1: bracket tag (non-empty ^\[([^\]]+)\] per D-09)
  SELECT collection_id FROM maplify.collection_rule
   WHERE match_kind = 'bracket'
     AND comments ~ '^\[([^\]]+)\]'
     AND match_value = (regexp_match(comments, '^\[([^\]]+)\]'))[1]
  UNION ALL
  -- Precedence 2: trailing attribution ("Trusted Observer" phrase)
  SELECT collection_id FROM maplify.collection_rule
   WHERE match_kind = 'attribution'
     AND comments ~ match_value
  UNION ALL
  -- Precedence 3: structured source code
  SELECT collection_id FROM maplify.collection_rule
   WHERE match_kind = 'source'
     AND match_value = source
  LIMIT 1;
$$;

-- =====================================================================
-- 3pre. NEW COLLECTION: whale-alert (census sign-off, 2026-06-19)
--    source 'whale_alert' (2484 rows) maps to a new collection distinct from
--    whale-alert-global / whale-alert-alaska (both kind='detector', org=NULL).
--    Must be inserted BEFORE the source rule that references it.
-- =====================================================================
INSERT INTO public.collections (slug, name, kind)
VALUES ('whale-alert', 'Whale Alert', 'detector')
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- 3. Seed maplify.collection_rule from human-confirmed census (plan 11-02)
--    Collection IDs resolved via slug subquery — NEVER hardcoded integers.
--    ON CONFLICT (match_kind, match_value) DO NOTHING for idempotency.
--
--    Excluded rows (operator decisions, 2026-06-19):
--      STAY_NULL: source 'FARPB' (384 rows) — intentionally unresolved
--      DROP:      source 'wras'  (50 rows)  — handled in plan 11-04
-- =====================================================================

-- 3a. Bracket tag rules (match_kind='bracket')
--     Includes the 4 Orca Network typo variants (all → orca-network)
--     and the 11 acronym stubs (psws/mcw/cww/wssji/hiws/sbw/wa/ssch/sa/psww/bremerton-fb)
INSERT INTO maplify.collection_rule (match_kind, match_value, collection_id)
VALUES
  -- Orca Network variants (typos as separate rows — exact-match only, D-09)
  ('bracket', 'Orca Network',          (SELECT id FROM public.collections WHERE slug = 'orca-network')),
  ('bracket', ' Orca Network',         (SELECT id FROM public.collections WHERE slug = 'orca-network')),
  ('bracket', 'Orca Networ',           (SELECT id FROM public.collections WHERE slug = 'orca-network')),
  ('bracket', 'Orca Networks',         (SELECT id FROM public.collections WHERE slug = 'orca-network')),
  ('bracket', 'Orca Neteork',          (SELECT id FROM public.collections WHERE slug = 'orca-network')),
  -- Named collections
  ('bracket', 'Orcasound',             (SELECT id FROM public.collections WHERE slug = 'orcasound')),
  ('bracket', 'MBARI',                 (SELECT id FROM public.collections WHERE slug = 'mbari')),
  ('bracket', 'Bremerton FB group',    (SELECT id FROM public.collections WHERE slug = 'bremerton-fb')),
  -- Acronym stubs (name expansions DEFERRED per operator, 2026-06-19)
  ('bracket', 'PSWS',                  (SELECT id FROM public.collections WHERE slug = 'psws')),
  ('bracket', 'MCW',                   (SELECT id FROM public.collections WHERE slug = 'mcw')),
  ('bracket', 'CWW',                   (SELECT id FROM public.collections WHERE slug = 'cww')),
  ('bracket', 'WSSJI',                 (SELECT id FROM public.collections WHERE slug = 'wssji')),
  ('bracket', 'HIWS',                  (SELECT id FROM public.collections WHERE slug = 'hiws')),
  ('bracket', 'SBW',                   (SELECT id FROM public.collections WHERE slug = 'sbw')),
  ('bracket', 'WA',                    (SELECT id FROM public.collections WHERE slug = 'wa')),
  ('bracket', 'SSCH',                  (SELECT id FROM public.collections WHERE slug = 'ssch')),
  ('bracket', 'SA',                    (SELECT id FROM public.collections WHERE slug = 'sa')),
  ('bracket', 'PSWW',                  (SELECT id FROM public.collections WHERE slug = 'psww'))
ON CONFLICT (match_kind, match_value) DO NOTHING;

-- 3b. Attribution rules (match_kind='attribution')
--     match_value is the phrase matched via comments ~ match_value (substring match)
--     Covers "Submitted by a/an <ORG> Trusted Observer" patterns (D-13)
INSERT INTO maplify.collection_rule (match_kind, match_value, collection_id)
VALUES
  ('attribution', 'Whale Alert Global',  (SELECT id FROM public.collections WHERE slug = 'whale-alert-global')),
  ('attribution', 'Whale Alert Alaska',  (SELECT id FROM public.collections WHERE slug = 'whale-alert-alaska')),
  ('attribution', 'TMMC',                (SELECT id FROM public.collections WHERE slug = 'tmmc')),
  ('attribution', 'Cascadia',            (SELECT id FROM public.collections WHERE slug = 'cascadia'))
ON CONFLICT (match_kind, match_value) DO NOTHING;

-- 3c. Source code rules (match_kind='source')
--     Only the curated whale_alert source code (D-11); FARPB is STAY_NULL; wras is DROP
INSERT INTO maplify.collection_rule (match_kind, match_value, collection_id)
VALUES
  ('source', 'whale_alert', (SELECT id FROM public.collections WHERE slug = 'whale-alert'))
ON CONFLICT (match_kind, match_value) DO NOTHING;

-- =====================================================================
-- 4. Acronym name backfill (D-10) — NO-OP this phase
--    The operator DEFERRED real-name expansions at 11-02 sign-off.
--    Only slug mapping was confirmed; actual organization names are unknown.
--    Stub collection names remain the uppercase acronym (PSWS, MCW, etc.).
--    This section is intentionally empty.
-- =====================================================================

-- =====================================================================
-- 5. public.contributors.inat_login — dedup key for iNat contributor rows (D-15)
--    Nullable: existing native contributors leave inat_login NULL.
--    UNIQUE constraint enforces idempotent ON CONFLICT (inat_login) DO NOTHING.
--    IF NOT EXISTS makes this idempotent if column was added in a dev environment.
-- =====================================================================
ALTER TABLE public.contributors
  ADD COLUMN IF NOT EXISTS inat_login TEXT UNIQUE;

-- =====================================================================
-- 6. inaturalist.mint_contributor — SECURITY DEFINER helper (D-15, D-16)
--    MANDATORY: SECURITY DEFINER + SET search_path = '' (empty string)
--    Reason: public.contributors has RLS enabled (20260203234153_individuals.sql line 12).
--    No INSERT policy exists for the postgres (pg_cron) role. Without SECURITY DEFINER
--    the INSERT is silently blocked by RLS (RESEARCH Pitfall 2).
--    Precedent: create_contributor_on_sign_in (LANGUAGE plpgsql SECURITY DEFINER SET search_path='')
--    Every object schema-qualified (public.contributors) because search_path = ''.
--    Standalone helper because the iNat ingest function uses BEGIN ATOMIC SQL which
--    cannot use PL/pgSQL control flow (RESEARCH Pitfall 5).
-- =====================================================================
CREATE OR REPLACE FUNCTION inaturalist.mint_contributor(
  inat_login text
) RETURNS integer LANGUAGE SQL VOLATILE SECURITY DEFINER
SET search_path = '' AS $$
  INSERT INTO public.contributors (name, inat_login)
  VALUES (inat_login, inat_login)
  ON CONFLICT (inat_login) DO NOTHING;
  SELECT id FROM public.contributors WHERE contributors.inat_login = $1;
$$;

-- =====================================================================
-- 7. Migration-resolved collection_id DEFAULTs (D-05)
--    Pattern: DO $$ BEGIN EXECUTE format(...) END $$ resolves slug→id at migration
--    time; the ALTER emits a plain integer literal (never a subquery in DEFAULT).
--    Mirrors Phase 10 provider_id DEFAULT pattern exactly (RESEARCH Pattern 1).
--    Three single-collection tables: iNat → 'inaturalist', native → 'salishsea-direct',
--    HappyWhale → 'happywhale'.
-- =====================================================================

-- inaturalist.observations → collection slug 'inaturalist'
DO $$ BEGIN
  EXECUTE format(
    'ALTER TABLE inaturalist.observations ALTER COLUMN collection_id SET DEFAULT %s',
    (SELECT id FROM public.collections WHERE slug = 'inaturalist')
  );
END $$;

-- public.observations (native) → collection slug 'salishsea-direct'
DO $$ BEGIN
  EXECUTE format(
    'ALTER TABLE public.observations ALTER COLUMN collection_id SET DEFAULT %s',
    (SELECT id FROM public.collections WHERE slug = 'salishsea-direct')
  );
END $$;

-- happywhale.encounters → collection slug 'happywhale'
DO $$ BEGIN
  EXECUTE format(
    'ALTER TABLE happywhale.encounters ALTER COLUMN collection_id SET DEFAULT %s',
    (SELECT id FROM public.collections WHERE slug = 'happywhale')
  );
END $$;
