-- Phase 9: Reference Table Foundation
-- Creates the provenance graph reference tables (providers, organizations, collections)
-- plus a nullable orcid column on the existing public.contributors.
-- Access control: ENABLE ROW LEVEL SECURITY + permissive SELECT policy per table (D-10).
-- The public schema is already PostgREST-exposed; no config changes needed (Pitfall 5).

-- =====================================================================
-- 1. collection_kind ENUM
-- Exactly five locked values (D-09: the sixth candidate was explicitly rejected).
-- PostgreSQL has no ALTER TYPE ... DROP VALUE; adding an unwanted value now would require a
-- destructive migration to remove. Enum is nullable on collections.kind so stubs
-- (un-decoded acronym channels) carry NULL kind until Phase 11 decodes them.
-- =====================================================================
-- NOTE: 'aggregator_ingest' is intentionally absent from this enum (D-09).
-- PostgreSQL cannot drop enum values; adding it now would require a destructive
-- migration to remove. SC-3 assertion verifies absence via a failed cast.
CREATE TYPE public.collection_kind AS ENUM (
  'facebook_group',
  'research_dataset',
  'acoustic_feed',
  'detector',
  'direct_app'
);

-- =====================================================================
-- 2. public.providers
-- Four fixed ingest providers. No kind column — slug is sufficient for
-- identity; Phase 11 resolver maps slug → behavior in TypeScript (D-discretion).
-- =====================================================================
CREATE TABLE public.providers (
  id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug VARCHAR(50)  NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL
);

ALTER TABLE public.providers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Providers are publicly readable"
  ON public.providers FOR SELECT TO anon, authenticated
  USING (true);

-- Seed: 4 providers (PROV-01). ON CONFLICT (slug) — natural key, NOT id (Pitfall 4).
INSERT INTO public.providers (slug, name)
VALUES
  ('direct',       'SalishSea.io Direct'),
  ('maplify',      'Maplify / conserve.io'),
  ('inaturalist',  'iNaturalist'),
  ('happywhale',   'HappyWhale')
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- 3. public.organizations
-- Parent institutions for named collections. url NOT NULL per ORG-01.
-- rights_holder_text is the display string used in EML associatedParty (Phase 12).
-- Organizations MUST be seeded before collections (Pitfall 3: FK subquery order).
-- =====================================================================
CREATE TABLE public.organizations (
  id                 INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug               VARCHAR(50)  NOT NULL UNIQUE,
  name               VARCHAR(200) NOT NULL,
  url                TEXT         NOT NULL,
  rights_holder_text VARCHAR(200) NOT NULL
);

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Organizations are publicly readable"
  ON public.organizations FOR SELECT TO anon, authenticated
  USING (true);

-- Seed: 5 organizations (ORG-01). All have known public URLs. ON CONFLICT (slug).
INSERT INTO public.organizations (slug, name, url, rights_holder_text)
VALUES
  ('orca-network',  'Orca Network',                              'https://orcanetwork.org',          'Orca Network'),
  ('cascadia',      'Cascadia Research Collective',              'https://cascadiaresearch.org',     'Cascadia Research Collective'),
  ('tmmc',          'The Marine Mammal Center',                  'https://marinemammalcenter.org',   'The Marine Mammal Center'),
  ('mbari',         'Monterey Bay Aquarium Research Institute',  'https://mbari.org',                'MBARI'),
  ('orcasound',     'Orcasound',                                 'https://orcasound.net',            'Orcasound')
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- 4. public.collections
-- Shared registry of data channels — not 1:1 with providers (D-02).
-- kind nullable: stubs have NULL kind until Phase 11 decodes them (D-09).
-- organization_id nullable: Whale Alert and per-platform baselines have no org row.
-- Btree index on organization_id per FK-index skill rule — supports Phase 12 JOINs.
-- =====================================================================
CREATE TABLE public.collections (
  id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug            VARCHAR(100)           NOT NULL UNIQUE,
  name            VARCHAR(200)           NOT NULL,
  kind            public.collection_kind,           -- nullable: stubs carry NULL kind (D-09)
  organization_id INTEGER REFERENCES public.organizations(id)  -- nullable: stubs + Whale Alert (D-02)
);

CREATE INDEX ON public.collections (organization_id);

ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Collections are publicly readable"
  ON public.collections FOR SELECT TO anon, authenticated
  USING (true);

-- Seed: ~21 collection rows (COLL-01).
-- Named collections: organization_id resolved via slug subquery (Pitfall 3 avoided by
-- seeding organizations before collections above).
-- Acronym stubs: organization_id = NULL, kind = NULL (D-06).
-- ON CONFLICT (slug) DO NOTHING — reference rows are immutable (Pitfall 4, anti-DO UPDATE).
INSERT INTO public.collections (slug, name, kind, organization_id)
VALUES
  -- Named collections with organization (non-null kind, non-null org)
  ('orca-network',          'Orca Network',                              'facebook_group',   (SELECT id FROM public.organizations WHERE slug = 'orca-network')),
  ('cascadia',              'Cascadia Research Collective',              'research_dataset', (SELECT id FROM public.organizations WHERE slug = 'cascadia')),
  ('tmmc',                  'The Marine Mammal Center',                  'research_dataset', (SELECT id FROM public.organizations WHERE slug = 'tmmc')),
  ('orcasound',             'Orcasound',                                 'acoustic_feed',    (SELECT id FROM public.organizations WHERE slug = 'orcasound')),
  ('mbari',                 'Monterey Bay Aquarium Research Institute',  'research_dataset', (SELECT id FROM public.organizations WHERE slug = 'mbari')),
  -- Named collections without an org row (Whale Alert — ORCA Conservancy not seeded this phase)
  ('whale-alert-global',    'Whale Alert (Global)',                      'detector',         NULL),
  ('whale-alert-alaska',    'Whale Alert (Alaska)',                      'detector',         NULL),
  -- Per-provider baseline collections (D-03): one per non-aggregator provider
  ('inaturalist',           'iNaturalist',                               'direct_app',       NULL),
  ('happywhale',            'HappyWhale',                                'direct_app',       NULL),
  ('salishsea-direct',      'SalishSea.io Direct',                       'direct_app',       NULL),
  -- Acronym stubs (D-06): un-decoded Maplify bracket tags; Phase 11 fills name/org/kind
  ('psws',                  'PSWS',                                      NULL,               NULL),
  ('mcw',                   'MCW',                                       NULL,               NULL),
  ('cww',                   'CWW',                                       NULL,               NULL),
  ('wssji',                 'WSSJI',                                     NULL,               NULL),
  ('hiws',                  'HIWS',                                      NULL,               NULL),
  ('sbw',                   'SBW',                                       NULL,               NULL),
  ('wa',                    'WA',                                        NULL,               NULL),
  ('ssch',                  'SSCH',                                      NULL,               NULL),
  ('sa',                    'SA',                                        NULL,               NULL),
  ('psww',                  'PSWW',                                      NULL,               NULL),
  ('bremerton-fb',          'Bremerton FB group',                        NULL,               NULL)
ON CONFLICT (slug) DO NOTHING;

-- =====================================================================
-- 5. Extend public.contributors with nullable orcid column (D-11)
-- IF NOT EXISTS makes this idempotent if column was added in a dev environment.
-- No NOT NULL constraint — ORCID values are populated later (D-11).
-- No CHECK constraint for ORCID format — deferred to when values are populated
-- (format edge cases unknown; see Column Design in 09-RESEARCH.md).
-- No index — 28 native contributors is below any meaningful btree threshold.
-- =====================================================================
ALTER TABLE public.contributors
  ADD COLUMN IF NOT EXISTS orcid TEXT;
