-- Phase 2: Identification foundation (sightings ↔ catalog).
--
-- An identification is a CLAIM that a subject (individual XOR social group) was
-- (or was not) present at an occurrence, with fully decomposed provenance kept
-- distinct: WHO asserts it (authority), WHAT evidence it rests on, HOW we
-- captured it (method), and HOW trusted it is (verification status). Regex
-- extraction from sighting text is ONE low-trust input, never the mechanism:
-- the public.occurrence_identifications view unions stored claims with live
-- regex candidates, stored rows overriding candidates.
--
-- This also transitions matriline social_groups from the coarse Phase-1 T-base
-- scheme to per-mother descent groups — derived deterministically from
-- public.individuals.mother_id (no external file), atomic under `db push`. On a
-- freshly-migrated (empty individuals) DB it is a no-op; the seed then creates
-- per-mother groups directly. On a populated DB (prod) it migrates in place.
--
-- Honesty invariant (CONTEXT.md, rights-policy §2.4): a regex hit is a
-- 'candidate' identification with evidence 'text_mention', never presented as a
-- validated identification / organismID.

-- ============================================================================
-- enums (values LOCKED: no ALTER TYPE ... DROP VALUE)
-- ============================================================================
CREATE TYPE public.identification_evidence AS ENUM
  ('text_mention', 'photograph', 'cv_match', 'field_observation');

CREATE TYPE public.identification_method AS ENUM
  ('text_extraction', 'manual', 'cv', 'upstream_import');

CREATE TYPE public.identification_status AS ENUM
  ('candidate', 'validated', 'rejected');

-- ============================================================================
-- normalize_designation — map a sighting code to its padded catalog key.
-- Extracted identifiers are un-padded ('T65A5','T65As'); catalog codes are
-- padded ('T065A5'). Pad only the first numeric block of T-codes; uppercase so
-- a lowercased hex-letter block matches; pass CRC/J/K/L/CA/AM through. The
-- trailing matriline 's' is stripped by the view, not here.
-- ============================================================================
CREATE OR REPLACE FUNCTION public.normalize_designation(code text)
  RETURNS text
  LANGUAGE sql
  IMMUTABLE
  SET search_path = ''
  AS $$
  SELECT CASE
    WHEN u ~ '^T\d' THEN
      'T' || lpad((regexp_match(u, '^T(\d+)'))[1], 3, '0') || substring(u FROM '^T\d+(.*)$')
    ELSE u
  END
  FROM (SELECT upper(btrim(code)) AS u) s;
$$;

-- ============================================================================
-- identifications — one row per claim
-- ============================================================================
CREATE TABLE public.identifications (
  id                   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  occurrence_id        TEXT NOT NULL,                       -- → public.occurrences (a VIEW; no FK)
  individual_id        INTEGER REFERENCES public.individuals (id),
  social_group_id      INTEGER REFERENCES public.social_groups (id),
  is_present           BOOLEAN NOT NULL DEFAULT true,       -- false = absence ("T65As minus A5")
  evidence             public.identification_evidence,      -- what the claim rests on
  method               public.identification_method NOT NULL, -- how WE captured it
  status               public.identification_status NOT NULL DEFAULT 'candidate', -- trust (ek3)
  asserted_by_party_id INTEGER REFERENCES public.parties (id), -- who/authority; NULL = report-implicit
  confidence           REAL,                                 -- e.g. CV score; NULL for text
  code                 TEXT,                                 -- raw extracted code, for traceability
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT identification_subject_ck CHECK (num_nonnulls(individual_id, social_group_id) = 1)
);
CREATE INDEX ON public.identifications (occurrence_id);
CREATE INDEX ON public.identifications (individual_id);
CREATE INDEX ON public.identifications (social_group_id);
CREATE INDEX ON public.identifications (asserted_by_party_id);
ALTER TABLE public.identifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Identifications are publicly readable"
  ON public.identifications FOR SELECT TO anon, authenticated USING (true);

-- ============================================================================
-- Per-mother matriline transition (derived from individuals.mother_id).
-- Idempotent and safe: pure set logic over in-DB catalog data, one migration,
-- atomic. No-op when individuals is empty.
-- ============================================================================

-- 1. wipe matriline memberships (re-derived below); named/ecotype untouched
DELETE FROM public.group_memberships gm
  USING public.social_groups sg
  WHERE gm.group_id = sg.id AND sg.kind = 'matriline';

-- 2. detach any matriline parent pointer (re-derived below) to free deletes
UPDATE public.social_groups SET parent_group_id = NULL WHERE kind = 'matriline';

-- 3. delete matriline groups whose designation is not a per-mother anchor
--    (a per-mother anchor = an individual who is some individual's mother)
DELETE FROM public.social_groups sg
  WHERE sg.kind = 'matriline'
    AND sg.designation NOT IN (
      SELECT DISTINCT m.primary_designation
      FROM public.individuals child
      JOIN public.individuals m ON m.id = child.mother_id
    );

-- 4. create a matriline group per mother (keyed by the anchor's designation)
INSERT INTO public.social_groups (kind, designation, notes)
  SELECT 'matriline', m.primary_designation, NULL
  FROM public.individuals child
  JOIN public.individuals m ON m.id = child.mother_id
  GROUP BY m.primary_designation
  ON CONFLICT (designation) DO UPDATE SET kind = EXCLUDED.kind;

-- 5. anchor each matriline to the individual it is named for
UPDATE public.social_groups sg SET anchor_individual_id = i.id
  FROM public.individuals i
  WHERE sg.kind = 'matriline' AND i.primary_designation = sg.designation;

-- 6. parent = the ecotype by default...
UPDATE public.social_groups sg
  SET parent_group_id = (SELECT id FROM public.social_groups WHERE kind = 'ecotype' AND designation = 'Biggs')
  WHERE sg.kind = 'matriline';

-- 6b. ...overridden by the anchor's own mother's matriline where she has one
UPDATE public.social_groups sg SET parent_group_id = parent.id
  FROM public.individuals anchor
  JOIN public.individuals mo ON mo.id = anchor.mother_id
  JOIN public.social_groups parent ON parent.kind = 'matriline' AND parent.designation = mo.primary_designation
  WHERE sg.kind = 'matriline' AND anchor.primary_designation = sg.designation;

-- 7. membership: each individual is a direct member of its mother's descent
--    group (transitive membership is derived later via mother_id recursion)
INSERT INTO public.group_memberships (group_id, individual_id, is_current, joined_year, basis)
  SELECT g.id, child.id, (child.life_status = 'alive'), child.born_latest, 'maternal'::public.membership_basis
  FROM public.individuals child
  JOIN public.individuals mo ON mo.id = child.mother_id
  JOIN public.social_groups g ON g.kind = 'matriline' AND g.designation = mo.primary_designation
  ON CONFLICT (group_id, individual_id) DO UPDATE SET
    is_current = EXCLUDED.is_current, joined_year = EXCLUDED.joined_year, basis = EXCLUDED.basis;

-- ============================================================================
-- occurrence_identifications — what the app reads.
-- Stored claims UNION live regex candidates, the latter only where no stored
-- claim exists for the same (occurrence, subject) — so a curator's validated /
-- rejected / absence row overrides the raw text hit. Unresolved codes
-- (CRC/JKL/uncataloged) resolve to no subject and are dropped here (see
-- occurrence_unresolved_codes).
-- ============================================================================
CREATE VIEW public.occurrence_identifications AS
WITH regex_candidates AS (
  SELECT
    o.id AS occurrence_id,
    ident.code AS code,
    d.individual_id AS individual_id,
    grp.id AS social_group_id
  FROM public.occurrences o
  CROSS JOIN LATERAL unnest(o.identifiers) AS ident(code)
  LEFT JOIN public.social_groups grp
    ON ident.code ~ 's$'
    AND grp.kind = 'matriline'
    AND grp.designation = public.normalize_designation(regexp_replace(ident.code, 's$', ''))
  LEFT JOIN public.designations d
    ON ident.code !~ 's$'
    AND d.code = public.normalize_designation(ident.code)
  WHERE d.individual_id IS NOT NULL OR grp.id IS NOT NULL
)
SELECT
  id, occurrence_id, individual_id, social_group_id, is_present,
  evidence, method, status, asserted_by_party_id, confidence, code, created_at
FROM public.identifications
UNION ALL
SELECT
  NULL::integer AS id,
  rc.occurrence_id,
  rc.individual_id,
  rc.social_group_id,
  true AS is_present,
  'text_mention'::public.identification_evidence AS evidence,
  'text_extraction'::public.identification_method AS method,
  'candidate'::public.identification_status AS status,
  NULL::integer AS asserted_by_party_id,
  NULL::real AS confidence,
  rc.code,
  NULL::timestamptz AS created_at
FROM regex_candidates rc
WHERE NOT EXISTS (
  SELECT 1 FROM public.identifications s
  WHERE s.occurrence_id = rc.occurrence_id
    AND s.individual_id IS NOT DISTINCT FROM rc.individual_id
    AND s.social_group_id IS NOT DISTINCT FROM rc.social_group_id
);

-- ============================================================================
-- occurrence_unresolved_codes — codes mentioned in sightings that resolve to no
-- catalog subject (CRC/humpback, J/K/L Southern Residents, uncataloged Bigg's).
-- Powers a "mentioned but not in catalog" surface; sizes the catalog gap.
-- ============================================================================
CREATE VIEW public.occurrence_unresolved_codes AS
SELECT o.id AS occurrence_id, ident.code
FROM public.occurrences o
CROSS JOIN LATERAL unnest(o.identifiers) AS ident(code)
LEFT JOIN public.social_groups grp
  ON ident.code ~ 's$'
  AND grp.kind = 'matriline'
  AND grp.designation = public.normalize_designation(regexp_replace(ident.code, 's$', ''))
LEFT JOIN public.designations d
  ON ident.code !~ 's$'
  AND d.code = public.normalize_designation(ident.code)
WHERE grp.id IS NULL AND d.individual_id IS NULL;
