name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
          VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: artifacts
          path: |
            ./dist
            ./supabase

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: production
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::648183724555:role/salishsea-deploy-action
          aws-region: us-west-2
      - run: ls
      - uses: supabase/setup-cli@v1
        with:
          version: 2.53.6
      - run: supabase link --project-ref "${PROJECT_REF}"
        env:
          PROJECT_REF: ${{ vars.SUPABASE_PROJECT_ID }}
      - run: supabase db push
      - name: Deploy to S3 and invalidate CloudFront
        env:
          DESTINATION_URL: s3://${{ vars.S3_BUCKET }}/site
          DISTRIBUTIION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          aws s3 sync --no-progress dist "${DESTINATION_URL}"
          aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths /
